### ISSUE TITLE
The name of the tabs does not change when user is moving between site pages 

### ISSUE THREAD

**Issue by DmitriyBondarenko** [TimchenkoSergey/KhNADU-KTM#4]
**Description**:  The name of the tab does not change when user is moving between site pages 

**Steps to reproduce**:

1. Go to KhNADU-KTM/prod/index.html

2. Moving between pages 

3. Pay attention on the tab

**Actual result**:  The name of tab does not change 
**Expected result**: The name of tab is changed
**Severity**: Minor
**Attachment**: 
![sh1](https://cloud.githubusercontent.com/assets/25886751/23271626/cf53a09a-fa00-11e6-8d8a-82a21a0919b4.jpg)

**Comment by TimchenkoSergey** [comment]
This problem will be solved when the site will be on the server
