### ISSUE TITLE
The line with photos does not scale well

### ISSUE THREAD

**Issue by DmitriyBondarenko** [TimchenkoSergey/KhNADU-KTM#5]
**Description**: The line with photos on the page "Наука/Научная деятельность" badly scaled when the page zoom out.

**Steps to reproduce**:

1.  Go to KhNADU-KTM/prod/science.html#activity

2. Reduce the size of the page

3. Pay attention on the line with photos

**Actual result**: The line with photos does not adapt to the scale
**Expected result**: The line with photos adapt to the scale
**Severity**: Minor
**Attachment**:
![sh2](https://cloud.githubusercontent.com/assets/25886751/23273234/e73e8ca0-fa06-11e6-874e-fa623547e38b.jpg)

**Comment by DmitriyBondarenko** [comment]
The same situation is repeated on page: KhNADU-KTM/prod/article.html

**Attachment**:
![sh4](https://cloud.githubusercontent.com/assets/25886751/23313724/8913bf3a-fac7-11e6-968f-e346340c143f.jpg)

**Comment by TimchenkoSergey** [comment]
Task solved
