### ISSUE TITLE
The sidebar is not adapted to the elements of design on the main page

### ISSUE THREAD

**Issue by DmitriyBondarenko** [TimchenkoSergey/KhNADU-KTM#6]
**Description:** The sidebar is not adapted to the elements of design on the main page when the site is in mobile version.

**Steps to reproduce:**

1. Open the main page KhNADU-KTM/prod/index.html on the mobile phone or set the resolution > 768x1024

2. Open the sidebar

3. Scroll down the main page

4. Pay attention how the elements of design displayed

**Actual result:** The sidebar is not adapted to the elements of design
**Expected result:** The sidebar is correctly displayed
**Severity:** Major
**Attachment:**
![sh3](https://cloud.githubusercontent.com/assets/25886751/23277454/8c9166be-fa16-11e6-922f-162df512ea74.png)

**Comment by TimchenkoSergey** [comment]
Task solved
